version: '3.8'

services:
  faceid:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faceid_container
    restart: unless-stopped
    ports:
      - "8000:8000"  # Example port mapping (if needed)
    volumes:
      - .:/app       # Mount local project files into the container
    tty: true        # Keeps the container running for debugging
