version: '3.8'

services:
  faceid_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: faceid_cs  # Custom image name
    container_name: faceid_container
    volumes:
      - .:/app  # Mount the current directory to the container