@echo off
echo Setting up Face Recognition project...

echo Creating virtual environment...
python -m venv venv

echo Activating virtual environment...
call venv\Scripts\activate

echo Upgrading pip...
pip install --upgrade pip
pip install --upgrade setuptools

echo Install Cmake...
pip install cmake

echo Installing dependencies...
pip install -r requirements.txt

echo Running the project...
python main.py

pause